In [1]:
ls

 磁碟區 C 中的磁碟是 Local Disk
 磁碟區序號:  AEDB-C391

 C:\Users\Dory\DM\610530494 的目錄

2022/10/05  下午 09:01    <DIR>          .
2022/10/05  下午 09:01    <DIR>          ..
2022/10/05  下午 09:01    <DIR>          .ipynb_checkpoints
2022/09/22  上午 11:39            19,139 0922.ipynb
2022/10/05  下午 09:01                72 0929.ipynb
2022/09/22  上午 11:19                11 README.md
2022/09/22  上午 11:37           152,262 scores.csv
               4 個檔案         171,484 位元組
               3 個目錄  116,629,426,176 位元組可用


In [4]:
%%writefile hi.py   
print("hi 0929!")

Overwriting hi.py


In [3]:
run hi.py

hi 0929!


In [5]:
a = 1    

In [6]:
b = 2

In [7]:
whos

Variable   Type    Data/Info
----------------------------
a          int     1
b          int     2


In [8]:
pip install Numpy

Note: you may need to restart the kernel to use updated packages.


In [9]:
import numpy as np

In [10]:
np1 = np.array([1,2,3,4])
np2 = np.array((5,6,7,8))

In [11]:
print(np1)
print(np2)
print(type(np1), type(np2))

[1 2 3 4]
[5 6 7 8]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [13]:
np3 = np.arange(0, 31, 2)

In [14]:
np3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [15]:
np4 = np.linspace(1, 15, 5)

In [16]:
np4

array([ 1. ,  4.5,  8. , 11.5, 15. ])

In [17]:
np5 = np.zeros((5,))

In [18]:
np5

array([0., 0., 0., 0., 0.])

In [19]:
np6 = np.ones((5,))

In [20]:
np6

array([1., 1., 1., 1., 1.])

In [21]:
np7 = np.ones((5,3))

In [22]:
np7

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
listdata = [[1,2,3,4,5],
           [6,7,8,9,10]]
np8 = np.array(listdata)

In [24]:
listdata

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [ ]:
np8

In [25]:
print("維度", np8.ndim)
print("形狀", np8.shape)
print("數量", np8.size)

維度 2
形狀 (2, 5)
數量 10


In [26]:
np9 = np.arange(1, 21)
print(np9)
np10 = np9.reshape(4, 5)   
print(np10)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [27]:
#取一維資料
np10 =np.arange(0, 9)
print(np10)
print(np10[0])
print(np10[8])
print(np10[1:8])
print(np10[1:8:2])
print(np10[8:1:-1])
print(np10[:])
print(np10[4:])
print(np10[:4])

[0 1 2 3 4 5 6 7 8]
0
8
[1 2 3 4 5 6 7]
[1 3 5 7]
[8 7 6 5 4 3 2]
[0 1 2 3 4 5 6 7 8]
[4 5 6 7 8]
[0 1 2 3]


In [28]:
#取二維陣列資料

np11 = np.arange(1, 21).reshape(5, 4)
print(np11,"\n")
print(np11[0, 2],"\n")
print(np11[1, 2],"\n")
print(np11[0][2],"\n")
print(np11[1:3, 2],"\n")
print(np11[1:3, 1:3],"\n")
print(np11[::2, ::2],"\n")
print(np11[:, 2],"\n")
print(np11[1, :],"\n")
print(np11[:, :])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]] 

3 

7 

3 

[ 7 11] 

[[ 6  7]
 [10 11]] 

[[ 1  3]
 [ 9 11]
 [17 19]] 

[ 3  7 11 15 19] 

[5 6 7 8] 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [30]:
np12 = np.genfromtxt('score.csv', delimiter=',', skip_header=1)

In [31]:
np12

array([[ 1., 87., 85., 82.],
       [ 2., 92., 87., 90.],
       [ 3., 80., 91., 87.],
       [ 4., 78., 82., 95.],
       [ 5., 88., 89., 90.],
       [ 6., 82., 87., 88.],
       [ 7., 90., 92., 82.],
       [ 8., 87., 80., 90.],
       [ 9., 95., 78., 87.],
       [10., 90., 88., 95.],
       [11., 88., 89., 75.],
       [12., 82., 91., 66.],
       [13., 90., 82., 87.],
       [14., 87., 89., 92.],
       [15., 95., 87., 80.],
       [16., 90., 92., 78.],
       [17., 82., 80., 88.],
       [18., 90., 78., 93.],
       [19., 67., 87., 95.],
       [20., 91., 82., 88.],
       [21., 82., 81., 82.],
       [22., 79., 87., 90.],
       [23., 87., 92., 87.],
       [24., 92., 82., 95.],
       [25., 80., 90., 78.],
       [26., 78., 76., 91.],
       [27., 66., 90., 82.],
       [28., 89., 77., 89.],
       [29., 87., 95., 87.],
       [30., 73., 90., 92.]])

In [35]:
np13 = np.genfromtxt('00878.TW.csv', delimiter=',', skip_header=1)

In [36]:
np13

array([[          nan, 1.5000000e+01, 1.5000000e+01, ..., 1.5000000e+01,
        1.5000000e+01, 0.0000000e+00],
       [          nan, 1.4990000e+01, 1.4990000e+01, ..., 1.4990000e+01,
        1.4990000e+01, 0.0000000e+00],
       [          nan, 1.4980000e+01, 1.4980000e+01, ..., 1.4980000e+01,
        1.4980000e+01, 0.0000000e+00],
       ...,
       [          nan, 1.7350000e+01, 1.7400000e+01, ..., 1.7320000e+01,
        1.7320000e+01, 1.9682412e+07],
       [          nan, 1.7500000e+01, 1.7549999e+01, ..., 1.7250000e+01,
        1.7250000e+01, 3.4420055e+07],
       [          nan, 1.7100000e+01, 1.7139999e+01, ..., 1.7080000e+01,
        1.7080000e+01, 9.0933910e+07]])